feat: readable assertions
with `const ::core::panic` stablized a while back alongside `const fn`
we can emit very readable assertions about size, align, and offset.

example:
```
   Compiling example-regression-test1 v0.8.0
(C:\Users\ryexc\Projects\zngur\examples\regression_test1)
error[E0080]: evaluation panicked: zngur declared size of
crate::FieldTypeC is incorrect: expected 11 , real size is 12
    --> examples\regression_test1\src\generated.rs:1041:1
     |
1041 | __zngur_assert_size!(crate::FieldTypeC, 11);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of
`generated::_` failed here
     |
     = note: this error originates in the macro
`$crate::panic::panic_2021` which comes from the expansion of the macro
`__zngur_assert_size` (in Nightly builds, run with -Z macro-backtrace
for more info)

error[E0080]: evaluation panicked: zngur declared align of
crate::FieldTypeC is incorrect: expected 8 , real align is 4
    --> examples\regression_test1\src\generated.rs:1042:1
     |
1042 | __zngur_assert_align!(crate::FieldTypeC, 8);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of
`generated::_` failed here
     |
     = note: this error originates in the macro
`$crate::panic::panic_2021` which comes from the expansion of the macro
`__zngur_assert_align` (in Nightly builds, run with -Z macro-backtrace
for more info)

error[E0080]: evaluation panicked: zngur declared offset of field buzz_1
in crate::FieldTypeC is incorrect: expected offset of 12 , real offset
is 0
    --> examples\regression_test1\src\generated.rs:1055:1
     |
1055 | __zngur_assert_field_offset!(crate::FieldTypeC, 12, buzz_1);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
evaluation of `generated::_` failed here
     |
     = note: this error originates in the macro
`$crate::panic::panic_2021` which comes from the expansion of the macro
`__zngur_assert_field_offset` (in Nightly builds, run with -Z
macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
```